### ISSUE TITLE
Document system requirements

### ISSUE THREAD

**Issue by kpcyrd** [fepitre/debrebuild#4]
hey! :)

I know that debrebuild.pl from devscripts had some requirements on package version (like certain features that aren't present in debian buster yet), is this also the case for debrebuild.py? Which version of debian would you currently recommend to run debrebuild?

Thanks!

**Comment by fepitre** [comment]
Hello,

I'm currently running it on `bullseye` notably with respect to latest `mmdebstrap` version. I've made several enhancements into `python-debian` that I currently keep a local copy under `libs` folder.  I'm currently waiting for https://packages.qa.debian.org/p/python-debian/news/20210628T083326Z.html to be in `bullseye` (if it would be one day?). In all the cases, I've a local branch where I'm cleaning stuff with respect to `python-debian` latest version and also where I'm using locations provided by my snapshot service. I should provide more materials to your issue very soon.

Cheers!

**Comment by fepitre** [comment]
@kpcyrd You may find requested info in the README. Don't hesitate to ask or notify if I would have forgot something. I hope the software will be stabilized soon to make a release. I've still few updates to do on the `snapshot` API side and also on the current `debrebuild` code but I hope that will happen soon.
