### ISSUE TITLE
No source info found for yelp-41.1-1

### ISSUE THREAD

**Issue by kpcyrd** [fepitre/debrebuild#6]
hi, I noticed that all runs of debrebuild.py started failing:
```
+ /debrebuild/debrebuild.py --output=/tmp/rebuilderd9Md0Wu/out --builder=mmdebstrap -- /tmp/rebuilderd9Md0Wu/inputs/yelp_41.1-1_amd64.buildinfo
No source info found for yelp-41.1-1
```
It seems it's trying to pull data from this url:
```
https://snapshot.notset.fr/mr/package/yelp/41.1-1/srcfiles?fileinfo=1
```

then tries to access the `fileinfo` field:
https://github.com/fepitre/debrebuild/blob/0fe54875f51ffcff413699475b60a49939166ef4/debrebuild.py#L305-L324

but the response I got for that url doesn't have this field:
```
{
  "_api": "0.3",
  "_comment": "notset"
}
```

**Comment by fepitre** [comment]
This was a snapshot instance issue. I had a service that failed after Debian upgrade.

**Comment by kpcyrd** [comment]
It's working again, thanks!

**Comment by kpcyrd** [comment]
It seems like it broke again, I'm getting this:
```
{
  "_api": "0.3",
  "_comment": "notset"
}
```

for this link:
```
https://snapshot.notset.fr/mr/package/yelp/41.1-1/srcfiles?fileinfo=1
```

**Comment by fepitre** [comment]
I'm having an issue with postgresql that I need to troubleshoot. It's happening now since last update.
