### ISSUE TITLE
Skipping tests

### ISSUE THREAD

**Issue by kpcyrd** [fepitre/debrebuild#7]
hi!

I've rebuilt about 33% of debian sid using debrebuild and noticed some packages get stuck during `dh_auto_test`, would it be possible to rebuild the package without running tests?

Thanks!

**Comment by fepitre** [comment]
I've also noticed a lot of failure on tests but this is certainly due to Docker. I'll see what I can do in the next weeks.

**Comment by fepitre** [comment]
New option: `--build-options-nocheck` with a test case https://gitlab.com/fepitre/debrebuild/-/jobs/1934467296. I took a failing one, e.g: https://rebuild.notset.fr/debian/logs/heimdal-7.7.0+dfsg-2.all-1636131637.log.
